name: all_in_one
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  get: ^4.1.4
  get_storage: ^2.0.2
  flutter_zoom_drawer: ^2.0.2+4
  
  rxdart: ^0.27.1


  # 전화걸기
  flutter_phone_direct_caller: ^2.0.0
  
  

  # x_flutter: ^0.0.7
  x_flutter:
    path: packages/subtrees/x_flutter

  user:
    path: packages/user

  widgets:
    path: packages/widgets

  services:
    path: packages/services
    
    

dev_dependencies:
  flutter_test:
    sdk: flutter

  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
flutter:
  uses-material-design: true
