name: all_in_one
description: A new Flutter project.

publish_to: "none"

version: 1.0.1+3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2

  get: ^4.1.4
  get_storage: ^2.0.2
  flutter_zoom_drawer: ^2.0.2+4
  
  rxdart: ^0.27.1

  # 아이콘 모음집
  fluttericon: ^2.0.0

  webview_flutter: ^2.0.8


  utils:
    path: packages/temp_services/utils
    

  x_flutter:
    path: packages/subtrees/x_flutter

  widgets:
    path: packages/widgets


  calculator:
    path: packages/features/calculator

  qr_code:
    path: packages/features/qr_code

  weather:
    path: packages/features/weather

  kakaomap_webview:
    path: packages/features/kakaomap_webview

  country_info:
    path: packages/features/country_info

  exchange_rate:
    path: packages/features/exchange_rate


  connection:
    path: packages/features/connection

  about:
    path: packages/features/about
  about_phone:
    path: packages/features/about_phone
    
dependency_overrides:
  # flutter_simple_calculator
  expressions: ^0.2.2

  # expressions
  rxdart: ^0.27.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter



flutter:
  uses-material-design: true
