name: about
description: about packages
version: 0.0.10
homepage: https://github.com/thruthesky/all_in_one
repository: https://github.com/thruthesky/all_in_one

publish_to: "none"

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
    
  package_info_plus: ^1.0.3
  device_info_plus: ^2.0.1
  

  widgets:
    path: ../../widgets

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


