name: country_picker
description: country_picker packages
version: 0.0.1
homepage: https://github.com/thruthesky/all_in_one
repository: https://github.com/thruthesky/all_in_one

# pub.dev 에 publish 하지 않음
publish_to: "none"

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  services:
    path: ../../services

  country_currency_pickers:
    path: ../../subtrees/country_currency_pickers

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

