name: analytics
description: analytics packages
version: 0.0.1
homepage: https://github.com/thruthesky/all_in_one
repository: https://github.com/thruthesky/all_in_one

publish_to: "none"

environment:
  sdk: ">=2.12.0 <3.0.0"
  
dependencies:
  flutter:
    sdk: flutter

  firebase_core: "^1.5.0"
  firebase_analytics: "^8.3.0"
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

