name: dynamic_links
description: dynamic links packages
version: 0.0.1
homepage: https://github.com/thruthesky/all_in_one
repository: https://github.com/thruthesky/all_in_one

publish_to: "none"

environment:
  sdk: ">=2.14.0 <3.0.0"
  
dependencies:
  flutter:
    sdk: flutter

  firebase_dynamic_links: ^2.0.9
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


