name: utils
description: utils packages
version: 0.0.1
homepage: https://github.com/thruthesky/all_in_one
repository: https://github.com/thruthesky/all_in_one

publish_to: "none"

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^2.0.2
  get: ^4.1.4


  # Dio
  dio: ^4.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
