name: chat
description: chat packages
version: 0.0.1
homepage: https://github.com/thruthesky/all_in_one
repository: https://github.com/thruthesky/all_in_one

publish_to: "none"

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: "^1.5.0"
  firebase_auth: "^3.0.2"
  firebase_database: ^8.0.0

  rxdart: ^0.27.1
  crypto: ^3.0.1
  flutter_chat_bubble: ^2.0.0
  cached_network_image: ^3.1.0
  flutter_keyboard_visibility: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
