name: user
description: User packages
version: 0.0.1
homepage: https://github.com/thruthesky/all_in_one
repository: https://github.com/thruthesky/all_in_one

# pub.dev 에 publish 하지 않음
publish_to: "none"

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.1.4
  get_storage: ^2.0.2

  # publish_to: none 이어야 path 사용 가능.
  x_flutter:
    path: ../x_flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
